model:
  variables:
    categorical:
      csp:
        - "a"
        - "b"
        - "c"
        - "d"
        - "e"
        - "f"
      gender:
        - "M"
        - "F"
      churn:
        - 0
        - 1
    numerical:
      - total amount
      - price
      - probability churn
  inference date: dates
service:
  requests per second: qps
  latency: latency
display:
  top-category: 4
